/* Prompt Vault Lists & Tasks full view. */
(()=>{
  "use strict";
  const M=PVListsModel,$=id=>document.getElementById(id),esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const TYPE_LABEL={bulleted:"Bulleted list",numbered:"Numbered list",checklist:"Checklist",kanban:"Kanban board",sticky:"Sticky notes"};
  let store=M.defaultStore(),folderId="lroot",fileId="",saveTimer=null;
  const folder=()=>M.findFolder(store.folders,folderId)||store.folders;
  const current=()=>M.findFile(store.folders,fileId)?.file||null;
  function toast(msg){const el=$("toast");el.textContent=msg;el.classList.add("on");setTimeout(()=>el.classList.remove("on"),1600)}
  function save(){clearTimeout(saveTimer);$("saveState").textContent="Saving…";saveTimer=setTimeout(()=>chrome.storage.local.set({[M.KEY]:store},()=>{saveTimer=null;$("saveState").textContent="Saved locally"}),120)}
  function touch(file){file.modified=Date.now();save()}
  function promptText(label,value=""){const x=window.prompt(label,value);return x===null?null:x.trim()}
  function renderFolders(){
    const walk=(n,depth)=>`<div class="folder ${n.id===folderId?'on':''}" data-folder="${esc(n.id)}" style="padding-left:${7+depth*13}px"><span>${(n.children||[]).length?'▾':'•'}</span><span class="name">${esc(n.name)}</span><span class="count">${(n.prompts||[]).length}</span></div>${(n.children||[]).map(c=>walk(c,depth+1)).join("")}`;
    $("folderTree").innerHTML=walk(store.folders,0)+`<div style="display:flex;gap:5px;padding:10px 4px"><button class="mini" id="renameFolder">Rename</button>${folderId!=="lroot"?'<button class="mini danger" id="deleteFolder">Delete empty</button>':''}</div>`;
    $("folderTree").querySelectorAll("[data-folder]").forEach(el=>el.onclick=()=>{folderId=el.dataset.folder;fileId="";render()});
    $("renameFolder").onclick=()=>{const f=folder(),name=promptText("Rename folder",f.name);if(name){f.name=name;save();render()}};
    $("deleteFolder")?.addEventListener("click",()=>{if(!M.removeFolder(store.folders,folderId)){toast("Folder must be empty first");return}folderId="lroot";fileId="";save();render()});
  }
  function renderFiles(){
    const f=folder(),files=f.prompts||[];$("folderTitle").textContent=f.name;
    $("fileList").innerHTML=files.length?files.map((x,i)=>`<article class="file ${x.id===fileId?'on':''}" data-file="${esc(x.id)}"><div class="file-main"><div class="file-title">${esc(x.title)}</div><div class="file-type">${esc(TYPE_LABEL[x.type]||x.type)}</div></div><div><button class="mini" data-file-up="${esc(x.id)}" ${i===0?'disabled':''}>↑</button><button class="mini" data-file-down="${esc(x.id)}" ${i===files.length-1?'disabled':''}>↓</button><button class="mini danger" data-file-del="${esc(x.id)}">×</button></div></article>`).join(""):'<div class="empty">This folder is empty. Choose a type above and create the first file.</div>';
    $("fileList").querySelectorAll("[data-file] .file-main").forEach(el=>el.onclick=()=>{fileId=el.closest("[data-file]").dataset.file;render()});
    $("fileList").querySelectorAll("[data-file-up],[data-file-down]").forEach(el=>el.onclick=e=>{e.stopPropagation();const id=el.dataset.fileUp||el.dataset.fileDown,i=files.findIndex(x=>x.id===id),to=el.dataset.fileUp!==undefined?i-1:i+1;if(M.move(files,i,to)){save();render()}});
    $("fileList").querySelectorAll("[data-file-del]").forEach(el=>el.onclick=e=>{e.stopPropagation();const x=files.find(y=>y.id===el.dataset.fileDel);if(x&&window.confirm(`Delete “${x.title}”?`)){files.splice(files.indexOf(x),1);if(fileId===x.id)fileId="";save();render()}});
  }
  function itemRows(file){
    return `<div class="add-row"><input id="addItemText" placeholder="Add an item…"><button id="addItem">Add</button></div><div id="items">${file.items.map((x,i)=>`<div class="list-row" data-item="${esc(x.id)}">${file.type==='checklist'?`<input type="checkbox" data-done ${x.done?'checked':''}>`:`<span class="num">${file.type==='numbered'?(i+1)+'.':'•'}</span>`}<input type="text" data-text value="${esc(x.text)}"><span class="row-actions"><button class="mini" data-up ${i===0?'disabled':''}>↑</button><button class="mini" data-down ${i===file.items.length-1?'disabled':''}>↓</button><button class="mini danger" data-del>×</button></span></div>`).join("")}</div>`;
  }
  function wireItems(file){
    const add=()=>{const input=$("addItemText"),text=input.value.trim();if(!text)return;file.items.push(M.normalizeItem({text}));input.value="";touch(file);renderEditor()};
    $("addItem").onclick=add;$("addItemText").onkeydown=e=>{if(e.key==="Enter")add()};
    $("items").querySelectorAll("[data-item]").forEach(row=>{const item=file.items.find(x=>x.id===row.dataset.item),idx=()=>file.items.indexOf(item);row.querySelector("[data-text]").onchange=e=>{item.text=e.target.value;touch(file)};row.querySelector("[data-done]")?.addEventListener("change",e=>{item.done=e.target.checked;touch(file)});row.querySelector("[data-up]").onclick=()=>{if(M.move(file.items,idx(),idx()-1)){touch(file);renderEditor()}};row.querySelector("[data-down]").onclick=()=>{if(M.move(file.items,idx(),idx()+1)){touch(file);renderEditor()}};row.querySelector("[data-del]").onclick=()=>{file.items.splice(idx(),1);touch(file);renderEditor()}});
  }
  function stickyHtml(file){return `<div class="add-row"><button id="addSticky">+ Sticky note</button></div><div class="sticky-grid" id="stickies">${file.items.map((x,i)=>`<article class="sticky" data-item="${esc(x.id)}" style="background:${esc(x.color)}"><textarea data-text placeholder="Type a note…">${esc(x.text)}</textarea><div class="sticky-actions"><select data-color><option value="#f3d37a" ${x.color==='#f3d37a'?'selected':''}>Gold</option><option value="#9ed6c6" ${x.color==='#9ed6c6'?'selected':''}>Mint</option><option value="#a8c7ef" ${x.color==='#a8c7ef'?'selected':''}>Blue</option><option value="#eab0bd" ${x.color==='#eab0bd'?'selected':''}>Rose</option></select><button data-up ${i===0?'disabled':''}>←</button><button data-down ${i===file.items.length-1?'disabled':''}>→</button><button data-del>×</button></div></article>`).join("")}</div>`}
  function wireStickies(file){$("addSticky").onclick=()=>{file.items.push(M.normalizeItem({text:"",color:"#f3d37a"}));touch(file);renderEditor()};$("stickies").querySelectorAll("[data-item]").forEach(el=>{const item=file.items.find(x=>x.id===el.dataset.item),idx=()=>file.items.indexOf(item);el.querySelector("[data-text]").onchange=e=>{item.text=e.target.value;touch(file)};el.querySelector("[data-color]").onchange=e=>{item.color=e.target.value;touch(file);renderEditor()};el.querySelector("[data-up]").onclick=()=>{if(M.move(file.items,idx(),idx()-1)){touch(file);renderEditor()}};el.querySelector("[data-down]").onclick=()=>{if(M.move(file.items,idx(),idx()+1)){touch(file);renderEditor()}};el.querySelector("[data-del]").onclick=()=>{file.items.splice(idx(),1);touch(file);renderEditor()}})}
  function kanbanHtml(file){return `<div class="add-row"><button id="addColumn">+ Column</button><span class="count">Drag cards within or between columns. Each column scrolls independently.</span></div><div class="board" id="board">${file.columns.map((col,ci)=>`<section class="column" data-column="${esc(col.id)}"><div class="column-head"><input data-column-title value="${esc(col.title)}"><button class="mini" data-col-left ${ci===0?'disabled':''}>←</button><button class="mini" data-col-right ${ci===file.columns.length-1?'disabled':''}>→</button><button class="mini danger" data-col-del>×</button></div><div class="cards" data-drop-column="${esc(col.id)}">${col.cards.map(card=>`<article class="card" draggable="true" data-card="${esc(card.id)}"><input data-card-text value="${esc(card.text)}"><div class="card-actions"><button class="mini danger" data-card-del>Delete</button></div></article>`).join("")}</div><div class="column-add"><input placeholder="Add a card…" data-card-new><button data-card-add>+</button></div></section>`).join("")}</div>`}
  function wireKanban(file){
    $("addColumn").onclick=()=>{const title=promptText("Column title","New column");if(title){file.columns.push(M.normalizeColumn({title,cards:[]}));touch(file);renderEditor()}};
    $("board").querySelectorAll("[data-column]").forEach(el=>{const col=file.columns.find(x=>x.id===el.dataset.column),idx=()=>file.columns.indexOf(col);el.querySelector("[data-column-title]").onchange=e=>{col.title=e.target.value.trim()||"Column";touch(file)};el.querySelector("[data-col-left]").onclick=()=>{if(M.move(file.columns,idx(),idx()-1)){touch(file);renderEditor()}};el.querySelector("[data-col-right]").onclick=()=>{if(M.move(file.columns,idx(),idx()+1)){touch(file);renderEditor()}};el.querySelector("[data-col-del]").onclick=()=>{if(col.cards.length){toast("Move or delete this column’s cards first");return}if(file.columns.length===1){toast("A board needs at least one column");return}file.columns.splice(idx(),1);touch(file);renderEditor()};const add=()=>{const input=el.querySelector("[data-card-new]"),text=input.value.trim();if(!text)return;col.cards.push(M.normalizeItem({text}));touch(file);renderEditor()};el.querySelector("[data-card-add]").onclick=add;el.querySelector("[data-card-new]").onkeydown=e=>{if(e.key==="Enter")add()}});
    $("board").querySelectorAll("[data-card]").forEach(el=>{const hit=()=>{for(const col of file.columns){const card=col.cards.find(x=>x.id===el.dataset.card);if(card)return{col,card}}};el.ondragstart=e=>{e.dataTransfer.setData("text/pv-list-card",el.dataset.card);e.dataTransfer.effectAllowed="move";el.classList.add("dragging")};el.ondragend=()=>el.classList.remove("dragging");el.querySelector("[data-card-text]").onchange=e=>{const x=hit();if(x){x.card.text=e.target.value;touch(file)}};el.querySelector("[data-card-del]").onclick=()=>{const x=hit();if(x){x.col.cards.splice(x.col.cards.indexOf(x.card),1);touch(file);renderEditor()}}});
    $("board").querySelectorAll("[data-drop-column]").forEach(zone=>{zone.ondragover=e=>{e.preventDefault();zone.classList.add("over")};zone.ondragleave=()=>zone.classList.remove("over");zone.ondrop=e=>{e.preventDefault();zone.classList.remove("over");const id=e.dataTransfer.getData("text/pv-list-card");const cards=[...zone.querySelectorAll("[data-card]:not(.dragging)")];let at=cards.length;for(let i=0;i<cards.length;i++){const r=cards[i].getBoundingClientRect();if(e.clientY<r.top+r.height/2){at=i;break}}if(M.moveCard(file,id,zone.dataset.dropColumn,at)){save();renderEditor()}}});
  }
  function renderEditor(){
    const file=current(),ed=$("editor");if(!file){ed.className="editor hidden";ed.innerHTML='<div class="empty">Choose a file or create one.</div>';return}ed.className="editor";
    const body=file.type==="kanban"?kanbanHtml(file):file.type==="sticky"?stickyHtml(file):itemRows(file);
    ed.innerHTML=`<div class="editor-head"><button id="mobileBack" class="mini">← Files</button><input id="titleInput" class="editor-title" value="${esc(file.title)}"><span class="file-type">${esc(TYPE_LABEL[file.type])}</span></div><div class="editor-body">${body}</div>`;
    $("titleInput").onchange=e=>{file.title=e.target.value.trim()||"Untitled";touch(file);renderFiles()};$("mobileBack").onclick=()=>{fileId="";renderEditor()};
    if(file.type==="kanban")wireKanban(file);else if(file.type==="sticky")wireStickies(file);else wireItems(file);
  }
  function render(){renderFolders();renderFiles();renderEditor()}
  $("newFolder").onclick=()=>{const name=promptText("New folder name");if(!name)return;folder().children.push({id:M.uid("lf"),name,children:[],prompts:[],color:""});save();render()};
  $("newFile").onclick=()=>{const type=$("newType").value,title=promptText(`Name this ${TYPE_LABEL[type]}`,TYPE_LABEL[type]);if(!title)return;const file=M.createFile(type,title);folder().prompts.push(file);fileId=file.id;save();render()};
  $("backBtn").onclick=()=>{if(history.length>1)history.back();else location.href="sidepanel.html?tab=lists"};
  $("closeBtn").onclick=()=>{window.close();setTimeout(()=>location.href="sidepanel.html?tab=lists",100)};
  window.addEventListener("keydown",e=>{if(e.key==="Escape"&&fileId&&!e.target.matches("input,textarea,select")){fileId="";renderEditor()}});
  chrome.storage.onChanged.addListener((changes,area)=>{if(area==="local"&&changes[M.KEY]&&!saveTimer){store=M.normalizeStore(M.clone(changes[M.KEY].newValue));render()}});
  chrome.storage.local.get([M.KEY],res=>{store=M.normalizeStore(M.clone(res[M.KEY]));render()});
})();
